### PR TITLE
Fix syntax error in Podspec when specifying multiple public_header_paths

### PR DESCRIPTION
**Pull request by rahul-malik**
## Goal

Address issues preventing Cocoapods integration which regressed 

## Changeset

The current podspec fails linting

```
$ pod spec lint --fail-fast BugsnagReactNative.podspec

 -> BugsnagReactNative (2.23.7)
    - ERROR | [iOS] file patterns: The `public_header_files` pattern did not match any file.
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 2 errors.

[!] React has been deprecated
```

### Changed
 We need to change the multiple paths in `s.public_header_files` to be comma-separated vs using the concatenation (`+`) operator which combines the multiple paths into a single path which matches no files in the repository.

## Tests

Re-ran linting to confirm `public_header_paths` issue was resolved

```
$ pod spec lint --fail-fast BugsnagReactNative.podspec

 -> BugsnagReactNative (2.23.7)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.

[!] React has been deprecated
```

### Alternative Approaches

N/A

### Outstanding Questions

- Are there plans to have the Bugsnag-cocoa repository as a dependency to avoid duplicating the public_header_paths?

### Linked issues

N/A

## Review

For the submitter, initial self-review:

- [  ] Commented on code changes inline explain the reasoning behind the approach
- [  ] Reviewed the test cases added for completeness and possible points for discussion
- [  ] A changelog entry was added for the goal of this pull request
- [  ] Check the scope of the changeset - is everything in the diff required for the pull request?
- This pull request is ready for:
  - [  ] Initial review of the intended approach, not yet feature complete
  - [  ] Structural review of the classes, functions, and properties modified
  - [ ] Final review

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency across platforms for structures or concepts added or modified
- [ ] Consistency between the changeset and the goal stated above
- [ ] Internal consistency with the rest of the library - is there any overlap between existing interfaces and any which have been added?
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Performance and complexity - are there any cases of unexpected O(n^3) when iterating, recursing, flat mapping, etc?
- [ ] Concurrency concerns - if components are accessed asynchronously, what issues will arise
- [ ] Thoroughness of added tests and any missing edge cases
- [ ] Idiomatic use of the language

### CODE REVIEW

**Comment by jparise** [comment]
Maybe `pod spec lint` could be added to the CI checks, too.

**Comment by xander-jones** [comment]
Hey @rahul-malik, thanks for the PR 👍  We shall review when priorities allow!

**Comment by tomlongridge** [comment]
@rahul-malik - I don't believe this change works as expected, despite the lint check.

If you run the script at `test/test-react-native-pod-build.sh` with the updated `BugsnagReactNative.podspec`, it builds however if you attempt to import these headers in the AppDelegate (as per the [online docs](https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration/#ios-native-installation)) then it seems to only find files from the first element of the `public_header_files` array (from what I can tell):

```
#import <BugsnagReactNative/BugsnagReactNative.h>
#import "BugsnagConfiguration.h"
```

I've been unable to find a syntax, other than a single string, that works. Interestingly the examples in the PodSpec DSL docs only show a single string (unlike `source_files`): https://www.rubydoc.info/github/CocoaPods/Core/master/Pod/Specification/DSL#public_header_files=-instance_method.

**Comment by johnkiely1** [comment]
Hi @rahul-malik 

Closing this as a fix is in the [latest release](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.23.10). This fix was first introduced in v2.23.8.

**Pull request closed without merging**
