### PR TITLE
Log isFatal to reported error

### PR DESCRIPTION
**Pull request by usrbowe**
## Goal

When logging JS errors, it's hard to see if app actually crashed. Or just some JS error was thrown, but user was not affected. 
Also if we use ErrorBoundary from React, we can handle lot of component errors, so app still keeps working.
This helps to understand, if app was crashed, and to prioritise fix on the error. 

### Added
Log `isFatal` via `report.metadata`

## Tests

Crash app with any unhandled JS error: `throw new Error('crash app')`

### Outstanding Questions

Is the `isFatal` reliable indicator? 

## Review

For the submitter, initial self-review:

- [ ] Commented on code changes inline explain the reasoning behind the approach
- [ ] Reviewed the test cases added for completeness and possible points for discussion
- [ ] A changelog entry was added for the goal of this pull request
- [ ] Check the scope of the changeset - is everything in the diff required for the pull request?
- This pull request is ready for:
  - [ ] Initial review of the intended approach, not yet feature complete
  - [ ] Structural review of the classes, functions, and properties modified
  - [ ] Final review

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency across platforms for structures or concepts added or modified
- [ ] Consistency between the changeset and the goal stated above
- [ ] Internal consistency with the rest of the library - is there any overlap between existing interfaces and any which have been added?
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Performance and complexity - are there any cases of unexpected O(n^3) when iterating, recursing, flat mapping, etc?
- [ ] Concurrency concerns - if components are accessed asynchronously, what issues will arise
- [ ] Thoroughness of added tests and any missing edge cases
- [ ] Idiomatic use of the language

### CODE REVIEW

**Comment by usrbowe** [comment]
**NOTE** the `/lib` is added just so I can use this fork for my project.

**Comment by abigail-bugsnag** [comment]
@usrbowe thanks for this. As you say, we will need to consider the reliability of the `isFatal` indicator and what the best way of addressing this is. We will discuss and get back to you.

**Comment by usrbowe** [comment]
@abigail-bugsnag I'll test this out in production app soon, so can get back with some more information later as well.
But I find this indicator crucial, to prioritise bugs in React Native.

**Comment by johnkiely1** [comment]
Hi @usrbowe 
Closing this off as the react native library has moved to be part of the bugsnag-js repo. However adding functionality for this is something that we will consider for a future release. 
Thanks again for the original PR.

**Pull request closed without merging**
