### PR TITLE
Add tvos example

### PR DESCRIPTION
**Pull request by fractalwrench**
Creates a (very basic) example for tvOS which notifies a non-fatal error. Additional setup steps required from the developer include:

- Opening their RN-generated xcodeproj, and adding `libz.tbd` and`libBugsnagReactNativeTvOs.a` to "Link binary with libraries" to the tvOS target
- Add `libReact.a` and remove version added by automatically generated RN project

To test this out will require replacing the contents of `node_modules/bugsnag_react_native/cocoa` with the `cocoa` folder in the project root.

See #152

### CODE REVIEW

**Comment by fractalwrench** [comment]
N.B. There isn't currently a module.modulemap as this was causing a clash with the iOS target.

**Comment by kattrali** [comment]
@fractalwrench what was the error message generated by having a modulemap?

**Comment by fractalwrench** [comment]
@kattrali the error message was "Redefinition of module Bugsnag". There were two identical module maps (one in the iOS folder, the other in the tvOS folder). Is there any way to offer the same functionality without renaming the exported tvOS module?

**Comment by fractalwrench** [comment]
@kattrali I've found a workaround for the modulemap issue by renaming the file and specifying its location in the xcodeproj Build Settings.

**Pull request closed without merging**
