### PR TITLE
turn off auto notify in debug mode

### PR DESCRIPTION
**Pull request by evollu**
just like handlePromiseRejections, prefer redbox in dev mode so it doesn't send the bug to bugsnag

### CODE REVIEW

**Comment by kattrali** [comment]
Thanks for the contribution, @evollu. The current behavior in debug mode should be to do both -- notify bugsnag and show the red box. Is that not happening? In general, `autoNotify` being on by default avoids confusion during initial setup where a user may not understand why errors are not immediately being caught, though the option is easily changed.

**Comment by evollu** [comment]
It is just annoying to receive error reporting email in while developing. Overriding default config is easy so you can close this if this is expected behavior

**Comment by wordofchristian** [comment]
@evollu It is recommended that after confirming that the bugsnag is working in development, to change [this setting](https://docs.bugsnag.com/platforms/react-native/configuration-options/#notifyreleasestages) so you won't get any more development notifications.

```js
configuration.notifyReleaseStages = ['beta', 'production'];
```

**Comment by kattrali** [comment]
Ah, thanks for the clarification @evollu. This behavior is intended but we can revisit if it becomes a usage problem.

@wordofchristian Thanks, that's also a good point. Maybe its something we can clarify in the initial usage guide.

Closing for now.

**Pull request closed without merging**
