### PR TITLE
Use h-char import for React/RCTVersion

### PR DESCRIPTION
**Pull request by matthova**
When manually linking bugsnag-react-native
```
#import "RCTVersion.h"
```

XCode throws the following error:
```
bugsnag-react-native/cocoa/BugsnagReactNative.m:4:9: 'RCTVersion.h' file not found
```

By instead using
```
#import <React/RCTConvert.h>
```
this build error is resolved

## Goal
Fix build error

## Changeset
Described above

## Tests
Tested by building for iOS

## Review

For the submitter, initial self-review:

- [x] Commented on code changes inline explain the reasoning behind the approach
- [x] Reviewed the test cases added for completeness and possible points for discussion
- [ ] A changelog entry was added for the goal of this pull request
- [x] Check the scope of the changeset - is everything in the diff required for the pull request?
- This pull request is ready for:
  - [x] Initial review of the intended approach, not yet feature complete
  - [x] Structural review of the classes, functions, and properties modified
  - [ ] Final review

For the pull request reviewer(s), this changeset has been reviewed for:

- [ ] Consistency across platforms for structures or concepts added or modified
- [ ] Consistency between the changeset and the goal stated above
- [ ] Internal consistency with the rest of the library - is there any overlap between existing interfaces and any which have been added?
- [ ] Usage friction - is the proposed change in usage cumbersome or complicated?
- [ ] Performance and complexity - are there any cases of unexpected O(n^3) when iterating, recursing, flat mapping, etc?
- [ ] Concurrency concerns - if components are accessed asynchronously, what issues will arise
- [ ] Thoroughness of added tests and any missing edge cases
- [ ] Idiomatic use of the language

### CODE REVIEW

**Comment by mattdyoung** [comment]
Hi @matthova 

I don't think this change shouldn't be necessary.

Can you share which versions of bugsnag-react-native and React Native itself you're using when you encounter this issue?

**Comment by matthova** [comment]
Using
    "bugsnag-react-native": "2.23.2",
	react-native 0.59

**Comment by mattdyoung** [comment]
@matthova 
I've been trying to reproduce the issue you describe on a clean project on React Native 0.59.x, but it seems to work for me.

Steps I've tried:
```
$ react-native init example --version react-native@0.59.10

$ cd example

$ npm install bugsnag-react-native --save

$ react-native link bugsnag-react-native
```

Added the following lines to `index.js`:
```
import { Client } from 'bugsnag-react-native';
const bugsnag = new Client('YOUR_API_KEY_HERE');
```
```
$ react-native run-ios
```

This builds and launches in an emulator without issue and also runs fine in XCode.

I've also gone on to integrate with the native layer too again without seeing the issue you describe:
https://docs.bugsnag.com/platforms/react-native/react-native/enhanced-native-integration/#ios-native-installation

Can you share steps to reproduce the issue which prompted you to raise this PR?

**Comment by matthova** [comment]
@mattdyoung thanks for checking it out. I believe the issue is related to our Podfile's setup

Near the beginning we're declaring
```ruby
install! 'cocoapods',
  :generate_multiple_pod_projects => true,
  :incremental_installation => true
```

We were able to resolve this github issue by adding the following to postinstall
```ruby
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      if target.name == "BugsnagReactNative"
        puts "Adding 'React-Core/React' to HEADER_SEARCH_PATHS for #{target}"
        append_header_search_path(target, '${PODS_ROOT}/Headers/Public/React-Core/React/')
      end
    end
  end
end
```

**Pull request closed without merging**
