### PR TITLE
call notify if notifyBlocking is not defined

### PR DESCRIPTION
**Pull request by evollu**
I don't know if this is right fix for #53

### CODE REVIEW

**Comment by the-simian** [comment]
@evollu did you test this yet? I'll try to take a look if you haven't

**Comment by evollu** [comment]
I'm using it now. seems fine. but IOS is using the none blocking notify

**Comment by kattrali** [comment]
Thank you for the contribution! iOS does not require two different methods since it writes to disk synchronously in the case that the application crashes, as opposed to the Android which immediately sends the request. This is the ideal solution.

**Comment by evollu** [comment]
cool good to know that

**Comment by the-simian** [comment]
Thanks ya'll

**Pull request closed without merging**
